/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Sample - OpenAPI 3.0
 * sample
 *
 * The version of the OpenAPI document: 1.0.11
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserFromJSON, UserToJSON } from './User';
/**
 * Check if a given object implements the GetUsersResponseInner interface.
 */
export function instanceOfGetUsersResponseInner(value) {
    var isInstance = true;
    isInstance = isInstance && 'data' in value;
    return isInstance;
}
export function GetUsersResponseInnerFromJSON(json) {
    return GetUsersResponseInnerFromJSONTyped(json, false);
}
export function GetUsersResponseInnerFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        data: json['data'].map(UserFromJSON),
    };
}
export function GetUsersResponseInnerToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        data: value.data.map(UserToJSON),
    };
}
