/**
 * Swagger Sample - OpenAPI 3.0
 * sample
 *
 * The version of the OpenAPI document: 1.0.11
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import type { GetUsersResponseInner } from '../models';
/**
 *
 */
export declare class UserApi extends runtime.BaseAPI {
    /**
     * get users list
     * get users
     */
    getUsersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetUsersResponseInner>>;
    /**
     * get users list
     * get users
     */
    getUsers(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetUsersResponseInner>;
}
